name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm install --global pnpm
      - run: pnpm --version

      - name: Install and build webview
        run: npm run pre-package:extension

      - name: Install vsce
        run: npm install -g  @vscode/vsce

      - name: Package Extension
        run: npm run package:extension

      - uses: actions/upload-artifact@v3
        name: Upload Package
        with:
          name: checking-extension-*.vsix
          path: .

