name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
#    runs-on: macos-latestyar

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Read version and commit sha
        run: |
          echo "HASH=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          echo "APP_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
          echo "APP_NAME=$(node -p -e "require('./package.json').name")" >> $GITHUB_ENV

      - name: Install yarn
        run: npm i -g yarn
      - run: yarn --version
      - run: yarn cache clean

      - name: Install pnpm
        run: npm install --global pnpm
      - run: pnpm --version

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Install and build webview
        run: npm run pre-package:extension

      - name: Package Extension
        run: yarn install --frozen-lockfile
      - run: vsce package --yarn

      - name: Set artifact name
        run: echo "ARTIFACT_NAME=$(echo "$APP_NAME-$APP_VERSION-$HASH.vsix")" >> $GITHUB_ENV
        
      - uses: actions/upload-artifact@v3
        name: Upload Package
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./checking-extension-*.vsix

